/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.progettoc3.vlv;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/** classe strandard springboot application */
@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SpringApplication.run(App.class, args);
    }
    
}
